resolver: lts-8.4

packages:
- '.'

extra-deps:
- intern-0.9.1.4
- storable-tuple-0.0.3.2

- ADPfusion-0.5.2.2
- AlignmentAlgorithms-0.1.0.0
- bimaps-0.1.0.2
- DPutils-0.0.1.0
- FormalGrammars-0.3.1.1
- GrammarProducts-0.1.1.3
- LinguisticsTypes-0.0.0.3
- NaturalLanguageAlphabets-0.1.1.0
- OrderedBits-0.0.1.2
- PrimitiveArray-0.8.0.1

